FROM registry.codeocean.com/codeocean/miniconda3:4.7.10-cuda10.1-cudnn7-ubuntu18.04
ARG DEBIAN_FRONTEND=noninteractive
RUN conda install tqdm scikit-image imageio opencv
RUN conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
RUN pip install matplotlib
RUN pip install pandas
RUN pip install scipy
RUN pip install absl-py==1.0.0
RUN pip install alabaster==0.7.12
RUN pip install argh==0.26.2
RUN pip install asn1crypto==1.3.0
RUN pip install astropy==4.0.1.post1
RUN pip install atomicwrites==1.4.0
RUN pip install attrs==19.3.0
RUN pip install Babel==2.8.0
RUN pip install backcall==0.2.0
RUN pip install backports.functools-lru-cache==1.6.1
RUN pip install backports.shutil-get-terminal-size==1.0.0
RUN pip install backports.tempfile==1.0
RUN pip install backports.weakref==1.0.post1
RUN pip install beautifulsoup4==4.9.1
RUN pip install bkcharts==0.2
RUN pip install bleach==3.1.5
RUN pip install boto==2.49.0
RUN pip install Bottleneck==1.3.2
RUN pip install brotlipy==0.7.0
RUN pip install cachetools==5.0.0
# RUN pip install certifi==2020.6.20
RUN pip install cffi==1.14.0
RUN pip install chardet==3.0.4
RUN pip install click==7.1.2
RUN pip install colorama==0.4.3
RUN pip install contextlib2==0.6.0.post1
RUN pip install cryptography==2.9.2
RUN pip install cycler==0.10.0
RUN pip install cytoolz==0.10.1
RUN pip install decorator==4.4.2
RUN pip install defusedxml==0.6.0
RUN pip install docutils==0.16
RUN pip install entrypoints==0.3
RUN pip install et-xmlfile==1.0.1
RUN pip install fastcache==1.1.0
RUN pip install filelock==3.0.12
RUN pip install flake8==3.8.3
RUN pip install Flask==1.1.2
RUN pip install freetype-py==2.2.0
RUN pip install fsspec==0.7.4
RUN pip install future==0.18.2
RUN pip install glob2==0.7
RUN pip install google-auth==2.6.0
RUN pip install google-auth-oauthlib==0.4.6
RUN pip install greenlet==0.4.16
RUN pip install grpcio==1.44.0
RUN pip install gym==0.22.0
RUN pip install gym-notices==0.0.4
RUN pip install h5py==2.10.0
RUN pip install HeapDict==1.0.1
RUN pip install imagesize==1.2.0
RUN pip install importlib-metadata==4.11.2
RUN pip install ipython-genutils==0.2.0
RUN pip install kiwisolver==1.2.0
RUN pip install lazy-object-proxy==1.4.3
RUN pip install libarchive-c==2.9
RUN pip install locket==0.2.0
RUN pip install loguru==0.6.0
RUN pip install Markdown==3.3.6
RUN pip install MarkupSafe==2.1.1
RUN pip install mccabe==0.6.1
RUN pip install mistune==0.8.4
RUN pip install mock==4.0.2
RUN pip install more-itertools==8.4.0
RUN pip install mpmath==1.1.0
RUN pip install msgpack==1.0.0
RUN pip install multipledispatch==0.6.0
RUN pip install nbconvert==5.6.1
RUN pip install nbformat==5.0.7
RUN pip install networkx==2.2
RUN pip install noise==1.2.2
RUN pip install nose==1.3.7
RUN pip install notebook==6.0.3
RUN pip install numba==0.50.1
RUN pip install numexpr==2.7.1
RUN pip install numpy==1.18.5
RUN pip install oauthlib==3.2.0
RUN pip install olefile==0.46
RUN pip install packaging==20.4
RUN pip install pandocfilters==1.4.2
RUN pip install parso==0.8.0
RUN pip install partd==1.1.0
RUN pip install path==13.1.0
RUN pip install pathlib2==2.3.5
RUN pip install pathtools==0.1.2
RUN pip install patsy==0.5.1
RUN pip install pep8==1.7.1
RUN pip install pexpect==4.8.0
RUN pip install pickleshare==0.7.5
RUN pip install pkginfo==1.5.0.1
RUN pip install pluggy==0.13.1
RUN pip install ply==3.11
RUN pip install prettytable==3.1.1
RUN pip install prometheus-client==0.8.0
RUN pip install prompt-toolkit==3.0.5
RUN pip install protobuf==3.19.4
RUN pip install psutil==5.7.0
RUN pip install ptyprocess==0.6.0
RUN pip install pyasn1==0.4.8
RUN pip install pyasn1-modules==0.2.8
RUN pip install pybullet==3.0.8
RUN pip install pycodestyle==2.6.0
RUN pip install pycollada==0.6
RUN pip install pycosat==0.6.3
RUN pip install pyflakes==2.2.0
RUN pip install pyglet==1.5.21
RUN pip install Pygments==2.6.1
RUN pip install PyOpenGL==3.1.0
RUN pip install pyparsing==2.4.7
RUN pip install pyrender==0.1.45
RUN pip install pyrsistent==0.16.0
RUN pip install PySocks==1.7.1
RUN pip install pytest==5.4.3
RUN pip install python-dateutil
RUN pip install pytz==2020.1
RUN pip install PyWavelets==1.1.1
RUN pip install pyxdg==0.26
RUN pip install PyYAML==5.3.1
RUN pip install pyzmq
RUN pip install QDarkStyle==2.8.1
RUN pip install QtAwesome==0.7.2
RUN pip install QtPy==1.9.0
RUN pip install requests-oauthlib==1.3.1
RUN pip install rope==0.17.0
RUN pip install rsa==4.8
RUN pip install ruamel-yaml
RUN pip install scikit-image==0.16.2
RUN pip install seaborn==0.10.1
RUN pip install SecretStorage==3.1.2
RUN pip install Send2Trash==1.5.0
RUN pip install simplegeneric==0.8.1
RUN pip install singledispatch==3.4.0.3
RUN pip install six==1.15.0
RUN pip install snowballstemmer==2.0.0
RUN pip install sortedcollections==1.2.1
RUN pip install sortedcontainers==2.2.2
RUN pip install soupsieve==2.0.1
RUN pip install sphinxcontrib-applehelp==1.0.2
RUN pip install sphinxcontrib-devhelp==1.0.2
RUN pip install sphinxcontrib-htmlhelp==1.0.3
RUN pip install sphinxcontrib-jsmath==1.0.1
RUN pip install sphinxcontrib-qthelp==1.0.3
RUN pip install sphinxcontrib-serializinghtml==1.1.4
RUN pip install traitlets
RUN pip install ujson==1.35
RUN pip install unicodecsv==0.14.1
RUN pip install urdfpy==0.0.22
RUN pip install urllib3==1.25.9
RUN pip install clyent==1.2.0
RUN pip install Rtree==0.9.7